#!/bin/bash
#
#SBATCH -J randomGreedy-FFMSP # A single job name for the array
#SBATCH -p main # Partition
#SBATCH -n 1 # one core
#--SBATCH-- -N 1 # on one node
#--SBATCH-- -t 0-0:30:00 # Running time of 30 mins
#--SBATCH-- --ntasks 4
#SBATCH --mem 8G # Memory request of 7 GB
#SBATCH --array=0-0
#SBATCH -o  bin_outFile_%A_CONF_%a.out 
#SBATCH -e  bin_errFile_%A_CONF_%a.err

#Declaring configurations
declare -a CONF_BIN=(
           " -alpha 0.87 " #  Tuning #  

        )
##Binary problems

#for i in {1..10}
#do
echo  /home/shared/sisadapt3/bin/random_greedy -i ${1} -th 0.85 -t 10 ${CONF_BIN[$SLURM_ARRAY_TASK_ID]} >"/home/shared/sisadapt3/Ejecuciones/greedy/th0.85/${2}_${SLURM_ARRAY_TASK_ID}"
/home/shared/sisadapt3/bin/random_greedy -i ${1} -th 0.85 -t 10 ${CONF_BIN[$SLURM_ARRAY_TASK_ID]} >>"/home/shared/sisadapt3/Ejecuciones/greedy/th0.85/${2}_${SLURM_ARRAY_TASK_ID}"
#done
