#!/bin/bash
#
#SBATCH -J SimulatedAnnealing-FFMSP # A single job name for the array
#SBATCH -p main # Partition
#SBATCH -n 1 # one core
#--SBATCH-- -N 1 # on one node
#--SBATCH-- -t 0-0:30:00 # Running time of 30 mins
#--SBATCH-- --ntasks 4
#SBATCH --mem 8G # Memory request of 7 GB
#SBATCH --array=0-0
#SBATCH -o  bin_outFile_%A_CONF_%a.out 
#SBATCH -e  bin_errFile_%A_CONF_%a.err

#Declaring configurations
declare -a CONF_BIN=(
           " -temperature 703 -cooling_rate 0.45 " #  Tuning #  

        )
##Binary problems

#for i in {1..10}
#do
echo  /home/shared/sisadapt3/bin/simulated_annealing simulated_annealing -i ${1} -t 10 -th 0.85 ${CONF_BIN[$SLURM_ARRAY_TASK_ID]} >"/home/shared/sisadapt3/Ejecuciones/metaheuristica/th0.85/${2}_${SLURM_ARRAY_TASK_ID}"
/home/shared/sisadapt3/bin/simulated_annealing simulated_annealing -i ${1} -t 10 -th 0.85 ${CONF_BIN[$SLURM_ARRAY_TASK_ID]} >>"/home/shared/sisadapt3/Ejecuciones/metaheuristica/th0.85/${2}_${SLURM_ARRAY_TASK_ID}"
#done
