#!/bin/bash
#
#SBATCH -J brkga-FFMSP # A single job name for the array
#SBATCH -p main # Partition
#SBATCH -n 1 # one core
#--SBATCH-- -N 1 # on one node
#--SBATCH-- -t 0-0:30:00 # Running time of 30 mins
#--SBATCH-- --ntasks 4
#SBATCH --mem 8G # Memory request of 7 GB
#SBATCH --array=0-0
#SBATCH -o  bin_outFile_%A_CONF_%a.out 
#SBATCH -e  bin_errFile_%A_CONF_%a.err

#Declaring configurations
declare -a CONF_BIN=(
           " -t 60 -p 453 -pe 0.07 -pm 0.19 -rhoe 0.67 -X_INTVL 382 -X_NUMBER 9 " #  Tuning #  

        )
##Binary problems

#for i in {1..10}
#do
echo  /home/shared/sisadapt3/bin/brkga brkga -i ${1} -th 0.75 ${CONF_BIN[$SLURM_ARRAY_TASK_ID]} >"/home/shared/sisadapt3/Ejecuciones/brkga/th0.75_60s/${2}_${SLURM_ARRAY_TASK_ID}"
/home/shared/sisadapt3/bin/brkga brkga -i ${1} -th 0.75 ${CONF_BIN[$SLURM_ARRAY_TASK_ID]} >>"/home/shared/sisadapt3/Ejecuciones/brkga/th0.75_60s/${2}_${SLURM_ARRAY_TASK_ID}"
#done
